# Generated by Django 3.1.5 on 2021-01-20 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('table.css', 'Таблица'), ('modern.css', 'Современный')], default='modern.css', max_length=30, verbose_name='Шаблон')),
                ('show_year', models.BooleanField(default=True, verbose_name='Показывать год')),
                ('cross', models.BooleanField(default=True, verbose_name='Зачеркивание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
