# Generated by Django 3.1.5 on 2021-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_color_event_eventcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('table.css', 'Таблица'), ('modern.css', 'Современный')], default='modern.css', max_length=30, verbose_name='Вид календаря'),
        ),
    ]
